In [ ]:
import numpy as np
test = np.array([1,2,3])
print(test)
print(type(test))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#Row vector
a = np.array([1,2,3,4,5])
print(a)
print(a.shape) #Number of dimensions
print(a.size)
print(a[0])

[1 2 3 4 5]
(5,)
5
1


In [ ]:
#Colunm vector
b = np.array([[1],[2],[5]])
print(b)
print(b.shape)
print(b.size)

[[1]
 [2]
 [5]]
(3, 1)
3


In [ ]:
#Vector generation : arrange(start, stop, step)
one2tenVector = np.arange(1,11)
print(one2tenVector)
oddNumber = np.arange(1,11,2)
print(oddNumber)

vec = np.arange(10,0,-1)
print(vec)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2  1]


In [ ]:
#Vector generation: linspace
y = np.linspace(1,100,100)
print(y)
print(y.size)
print(type(y[0]))

#int
y1 = np.linspace(1,100,100, dtype=int)
print(y1)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]
100
<class 'numpy.float64'>
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
#Create matrices
A = np.array([[1,2,3],[1,2,-5],[2,3,4]])
print(A)
print(A.shape)
print(A.size)
print(A[1][2])
print(A[1, 2])

[[ 1  2  3]
 [ 1  2 -5]
 [ 2  3  4]]
(3, 3)
9
-5
-5


In [ ]:
#Generating matrices
y1 = np.ones(5)
print(y1)
y2 = np.ones((3,3),dtype=int)
print(y2)

y3 = np.zeros(5)
print(y1)
y3 = np.zeros((3,3),dtype=int)
print(y3)

print(np.eye(3))

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1. 1. 1. 1. 1.]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# rand()
print(np.random.rand(5))
print(np.random.rand(3,3))


print(np.random.randn(5,5))

np.random.seed(2)
print(np.random.randint(1,100,10))
print(np.random.randint(1,100,(3,3)))


[0.20464863 0.61927097 0.29965467 0.26682728 0.62113383]
[[0.52914209 0.13457995 0.51357812]
 [0.18443987 0.78533515 0.85397529]
 [0.49423684 0.84656149 0.07964548]]
[[-7.47870949e-01  9.02525097e-03 -8.78107893e-01 -1.56434170e-01
   2.56570452e-01]
 [-9.88779049e-01 -3.38821966e-01 -2.36184031e-01 -6.37655012e-01
  -1.18761229e+00]
 [-1.42121723e+00 -1.53495196e-01 -2.69056960e-01  2.23136679e+00
  -2.43476758e+00]
 [ 1.12726505e-01  3.70444537e-01  1.35963386e+00  5.01857207e-01
  -8.44213704e-01]
 [ 9.76147160e-06  5.42352572e-01 -3.13508197e-01  7.71011738e-01
  -1.86809065e+00]]
[41 16 73 23 44 83 76  8 35 50]
[[96 76 86]
 [48 64 32]
 [91 21 38]]


In [ ]:
A = np.arange( 1,17).reshape(4,4)
print(A)
print(A[2,:])
print(A[:,3])
print(A[2,3])

#Sub matrices
y = A[1:3, 1:3]

print(y)
y[:,:] = 0
print(y)
print(A)

Z = A[1:3, 1:3].copy()
print(Z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 9 10 11 12]
[ 4  8 12 16]
12
[[ 6  7]
 [10 11]]
[[0 0]
 [0 0]]
[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9  0  0 12]
 [13 14 15 16]]
[[0 0]
 [0 0]]


In [ ]:
#Fancy Indexing/ Bolean valued indexing
a= np.linspace(0,1,11)
print(a)
print(a>0.5)
print(a[a>0.5])

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[False False False False False False  True  True  True  True  True]
[0.6 0.7 0.8 0.9 1. ]


In [ ]:
print(np.random.rand(12).reshape(3,4))


[[0.68302599 0.49856117 0.58679698 0.71975423]
 [0.25849809 0.54620732 0.40730783 0.17698462]
 [0.96963241 0.29701836 0.28786882 0.11619332]]


In [ ]:
A = np.arange(1,10).reshape(3,3)
print(A)
B = np.arange(9, 0,-1).reshape(3,3)
print(B)

print(np.concatenate((A,B)))
print(np.vstack((A,B)))

print(np.concatenate((A,B),axis=1))
print(np.hstack((A,B)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 2 3 9 8 7]
 [4 5 6 6 5 4]
 [7 8 9 3 2 1]]
[[1 2 3 9 8 7]
 [4 5 6 6 5 4]
 [7 8 9 3 2 1]]


In [ ]:
#Transpose

print(A)
print(A.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#Elementary functions
print(A)
print(B)
print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
print(np.dot(A,B))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
X = np.arange(1,17).reshape(4,4)
print(X)
print(np.mean(X))
print(np.mean(X, axis=0))  # Row wise mean
print(np.mean(X, axis=1))  # Colunm wise mean
print(np.cov(X))
print(np.sum(X))
print(np.sum(X, axis=0))
print(np.sum(X, axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
8.5
[ 7.  8.  9. 10.]
[ 2.5  6.5 10.5 14.5]
[[1.66666667 1.66666667 1.66666667 1.66666667]
 [1.66666667 1.66666667 1.66666667 1.66666667]
 [1.66666667 1.66666667 1.66666667 1.66666667]
 [1.66666667 1.66666667 1.66666667 1.66666667]]
136
[28 32 36 40]
[10 26 42 58]


In [ ]:
#Numerical equations
A = np.array([[1,2],[1,-1]])
print(A)
B = np.array([[10],[7]])
print(np.linalg.solve(A,B))

[[ 1  2]
 [ 1 -1]]
[[8.]
 [1.]]
